name: podcast_mobile_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  carbon_icons: ^0.0.1+2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.6
  material_design_icons_flutter: ^7.0.7296
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpg/
